### ISSUE TITLE
Number replacement does not work in lists

### ISSUE THREAD

**Issue by JoHoenk** [rhasspy/wyoming-vosk#11]
This issue is similar to #2 

Currently I have defined sentences in my de.yaml in the following format:
```
sentences:
  - {light} {brightness_numbers}
lists:
  light:
    values:
      - Küche Licht
      - Küche Hintergrund
  brightness_numbers:
    values:
      - in: fünf
        out: 5
      - in: zehn
        out: 10

```
But "zehn" does not get replaced in my command.
If I state "Küche Licht zehn" it forwards it directly to homeassistant and there the command is not recognized.
However If i enter "Küche Licht 10" in the sentence parser of the development options in HA it is recognized.

Do you have and idea why?

---
Current Setup:
Vosk Add-on 1.5.1
Correct sentences: 0
Limit sentences: true
Allow unknown: false
Debug logging: true
Home Assistant 2024.10.2
