### ISSUE TITLE
German Special Characters

### ISSUE THREAD

**Issue by JoHoenk** [rhasspy/wyoming-vosk#13]
Hi Guys,

first of all: awesome work here!

Currently I´m facing following issue with the special character 'ß' in sentence template:
```
brightness_numbers:
    values:
      - in: fünf
        out: 5
      - in: zehn
        out: 10
      - in: fünfzehn
        out: 15
      - in: zwanzig
        out: 20
      - in: fünfundzwanzig
        out: 25
      - in: dreißig
        out: 30
      - in: fünfunddreißig
        out: 35
``` 
When I run Vosk I get the following debug log entry, and the word recognition for 30 is also not working:
`vosk  | WARNING (VoskAPI:UpdateGrammarFst():recognizer.cc:308) Ignoring word missing in vocabulary: 'dreissig'`

However if I look in the dictionary on Huggingface it looks like the work `dreißig` is included in the model.
So it seems like something is replacing the ß. I already tried out different quotes but I always get this warning.

Does anybody have a hint for me?
