### ISSUE TITLE
Sentence in/out replacement doesn't work in lists

### ISSUE THREAD

**Issue by h3ndrik** [rhasspy/wyoming-vosk#2]
```yaml
sentences:
  - turn (on|off) {device}
  - in: lou mo ss  # lumos
    out: turn on all the lights
lists:
  device:
    values:
      - in: light
        out: bedroom room light
```

When I say 'turn off light' it transcribes as 'turn off light'. The replacement doesn't work. I'd expect the transcription to be changed to 'turn off bedroom room light'.

Doing the replacement in the sentences works: I say 'lumos' and it gives me 'turn on all the lights' back.

Vosk Add-on 1.3.0
Correct sentences: 0
Limit sentences: true
Allow unknown: false
Debug logging: true
Home Assistant 2023.10.5
