### ISSUE TITLE
Feature request: In/out replacement backreference

### ISSUE THREAD

**Issue by h3ndrik** [rhasspy/wyoming-vosk#4]
I'd like to do the following:

```yaml
sentences:
  - in: "dim <light>"
    out: "set <light> brightness to 25"
expansion_rules:
  light: "(livingroom light|kitchen light)"
```

As of now it literally writes `<light>` to the corrected transcript. I'd like this to work like named backreferences in a regex and replace the placeholder in the out part with whatever it captured earlier.

This should obviously work both for lists and expansion_rules. And maybe a short example could be added to the README.md
